<?php
/**
Plugin Name: Don't Log Bots
Plugin URI: https://github.com/YOURLS/dont-log-bots
Description: Do not log bots in stats
Version: 1.4
Requires at least: YOURLS 1.10
Requires PHP: 8.5
Author: Ozh, Leo Colomb, Suguru Hirahara
Author URI: http://yourls.org
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

/**
 * Check the current user agent against known crawlers and preview bots.
 */
function yp_dlb_is_bot() {
    // Get current User-Agent (may be missing on CLI / some requests; strtolower(null) is deprecated in PHP 8.1+)
    if ( empty( $_SERVER['HTTP_USER_AGENT'] ) ) {
        return false;
    }
    $current = strtolower( (string) $_SERVER['HTTP_USER_AGENT'] );

    // Known bot identifiers, all lowercase.
    // Example: 'googlebot' will match 'Googlebot/2.1 (+http://www.googlebot.com/bot.html)'
    $bots = array(
        // Legacy list of active crawlers and bots, refreshed with current bots.
        // picked up from: http://user-agent-string.info/list-of-ua/bots
        // also: http://myip.ms/browse/web_bots/Known_Web_Bots_Web_Bots_2014_Web_Spider_List.html
        '200please.com/bot',
        '360spider',
        '80legs.com/webcrawler',
        'a6-indexer',
        'aboundex',
        'aboutusbot',
        'addsearchbot',
        'addthis.com',
        'adressendeutschland.de',
        'adsbot-google',
        'adsbot-google-mobile',
        'ahrefsbot',
        'aihitbot',
        'alexa site audit',
        'amznkassocbot',
        'amazonbot',
        'analyticsseo.com',
        'antbot',
        'arabot',
        'applebot',
        'archive.org_bot',
        'archive.orgbot',
        'askpeterbot',
        'backlinkcrawler',
        'baidu.com/search/spider.html',
        'baiduspider',
        'baiduspider-render',
        'begunadvertising',
        'bingbot',
        'bingpreview',
        'bitlybot',
        'bixocrawler',
        'blekkobot',
        'blexbot',
        'brainbrubot',
        'browsershots',
        'bubing',
        'butterfly',
        'bufferbot',
        'bytespider',
        'careerbot',
        'catchbot',
        'ccbot',
        'cert figleafbot',
        'chatgpt-user',
        'changedetection.com/bot.html',
        'chilkat',
        'claritybot',
        'claudebot',
        'claude-searchbot',
        'classbot',
        'cliqzbot',
        'cms crawler',
        'coccoc',
        'compspybot',
        'cohere-ai',
        'crawler4j',        
        'crowsnest',
        'crystalsemanticsbot',
        'dataminr.com',
        'dataforseo',
        'daumoa',
        'deepseekbot',
        'discordbot',
        'duckassistbot',
        'easouspider',
        'embedly',
        'exabot',
        'exb language crawler',
        'ezooms',
        'facebookexternalhit',
        'facebookplatform',
        'fairshare',
        'feedfetcher',
        'feedly.com/fetcher.html',
        'feedlybot',
        'fetch',
        'flipboardproxy',
        'fyberspider',
        'genieo',
        'gigabot',
        'google page speed insights',
        'googlebot',
        'google-extended',
        'google-inspectiontool',
        'googleother',
        'gptbot',
        'grapeshot',
        'hatena-useragent',
        'hubspot connect',
        'hubspot links crawler',
        'hosttracker.com',
        'ia_archiver',
        'iframely',
        'icc-crawler',
        'ichiro',
        'immediatenet.com',
        'iltrovatore-setaccio',
        'infohelfer',
        'instapaper',
        'ixebot',
        'jabse.com crawler',
        'james bot',
        'jikespider',
        'jyxobot',
        'linkdex',
        'linkfluence',
        'linkedinbot',
        'loadimpactpageanalyzer',
        'luminate.com',
        'lycosa',
        'magpie-crawler',
        'mastodon',
        'mail.ru_bot',
        'meanpathbot',
        'mediapartners-google',
        'metageneratorcrawler',
        'metajobbot',
        'mj12bot',
        'meta-externalagent',
        'meta-externalfetcher',
        'mojeekbot',
        'mistralai-user',
        'msai.in',
        'msnbot-media',
        'musobot',
        'najdi.si',
        'nalezenczbot',
        'nekstbot',
        'netcraftsurveyagent',
        'netestate ne crawler',
        'netseer crawler',
        'nuhk',
        'obot',
        'oai-searchbot',
        'omgilibot',
        'openwebspider',
        'panscient.com',
        'perplexitybot',
        'petalbot',
        'phindbot',
        'pinterestbot',
        'parsijoo',
        'plukkie',
        'proximic',
        'psbot',
        'qirina hurdler',
        'qualidator.com',
        'queryseekerspider',
        'readability',
        'redditbot',
        'rogerbot',
        'sbsearch',
        'scrapy',
        'search.kumkie.com',
        'searchbot',
        'searchmetricsbot',
        'semrushbot',
        'serpstatbot',
        'seocheckbot',
        'seoengworldbot',
        'seokicks-robot',
        'seznambot',
        'shareaholic.com/bot',
        'shopwiki.com/wiki/help:bot',
        'showyoubot',
        'sistrix',
        'skypeuripreview',
        'sitechecker',
        'siteexplorer',
        'speedy spider',
        'socialbm_bot',
        'sogou web spider',
        'sogou',
        'sosospider',
        'spbot',
        'special_archiver',
        'spiderling',
        'slackbot-linkexpanding',
        'spinn3r',
        'spreadtrum',
        'steeler',
        'suma spider',
        'surveybot',
        'suggybot',
        'svenska-webbsido',
        'teoma',
        'telegrambot',
        'thumbshots',
        'tineye.com',
        'tiktokspider',
        'trendiction.com',
        'trendiction.de/bot',
        'turnitinbot',
        'tweetedtimes bot',
        'tweetmeme',
        'twitterbot',
        'uaslinkchecker',
        'umbot',
        'undrip bot',
        'unisterbot',
        'unwindfetchor',
        'urlappendbot',
        'vedma',
        'vkshare',
        'voilabot',
        'wbsearchbot',
        'wch web spider',
        'webcookies',
        'webcrawler at wise-guys dot nl',
        'webthumbnail',
        'wesee:search',
        'woko',
        'woobot',
        'woriobot',
        'wotbox',
        'y!j-bri',
        'y!j-bro',
        'y!j-brw',
        'y!j-bsc',
        'yacybot',
        'yahoo! slurp',
        'yahooysmcm',
        'yandexbot',
        'yats',
        'yeti',
        'yioopbot',
        'yodaobot',
        'youdaobot',
        'zb-1',
        'zeerch.com/bot.php',
        'zing-bottabot',
        'zumbot',

        // accessed when tweeted
        'ning/1.0',
        'yahoo:linkexpander:slingstone',
        'google-http-java-client/1.17.0-rc (gzip)',
        'js-kit url resolver',
        'htmlparser',
        'paperlibot',
        
        // xenu
        'xenu link sleuth',
    );
        
    // Check whether the current UA contains one of the known identifiers.
    foreach ( $bots as $bot ) {
        if ( str_contains( $current, $bot ) ) {
            return true;
        }
    }

    return false;
}

// Hook stuff in
yourls_add_filter( 'shunt_update_clicks', 'yp_dlb_skip_if_bot' );
yourls_add_filter( 'shunt_log_redirect', 'yp_dlb_skip_if_bot' );

// Skip if it's a bot
function yp_dlb_skip_if_bot( $pre = false ) {
    return false !== $pre ? $pre : yp_dlb_is_bot();
    // if anything but false is returned, functions using the two shunt_* filters will be short-circuited
}
